# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.

[[main]]
  name = "Home"
  url = "#first_sight"
  weight = 10

[[main]]
  name = "News"
  url = "news/"
  weight = 15

[[main]]
  name = "Research"
  url = "research/"
  weight = 20

[[main]]
  identifier = "team"
  name = "Team"
  weight = 30

[[main]]
  name = "Maomao Hu"
  parent = "team"
  url = "author/maomao-hu/"
  weight = 31

[[main]]
  name = "Lab members"
  parent = "team"
  url = "people/"
  weight = 32


[[main]]
  name = "Software"
  url = "software/"
  weight = 40

[[main]]
  name = "Publications"
  url = "publication/"     #direct to a page rather than a widget in home page
  weight = 50

[[main]]
  name = "Teaching"
  url = "teaching/"     #direct to a page rather than a widget in home page
  weight = 60

#[[main]]
#  name = "Gallery"
#  url = "gallery/"
#  weight = 60

[[main]]
  name = "Join"
  url = "join/"
  weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

[[main]]
  name = "Intranet"
  url = "https://nusu.sharepoint.com/sites/BIORonboarding"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 90
